void sceneRender()
{
	glEnable(GL_DEPTH_TEST);
	glEnable(GL_LIGHTING);
	glEnable(GL_COLOR_MATERIAL);
	//glShadeModel(GL_SMOOTH);
	glLightfv(GL_LIGHT0, GL_DIFFUSE, light_diffuse);
	glLightfv(GL_LIGHT0, GL_SPECULAR, light_specular);
	glLightfv(GL_LIGHT0, GL_LINEAR_ATTENUATION ,light_attenuation );
	glLightfv(GL_LIGHT2, GL_DIFFUSE, light_diffuse);
	glLightfv(GL_LIGHT2, GL_SPECULAR, light_specular);
	glLightfv(GL_LIGHT2, GL_LINEAR_ATTENUATION ,light_attenuation );
	glLightfv(GL_LIGHT1, GL_DIFFUSE, light_diffuse2);
	glLightfv(GL_LIGHT1, GL_SPECULAR, light_specular2);
	glLightfv(GL_LIGHT1, GL_LINEAR_ATTENUATION ,light_attenuation2 );
	glLightfv(GL_LIGHT3, GL_DIFFUSE, light_diffuse3);
	glLightfv(GL_LIGHT3, GL_SPECULAR, light_specular3);
	glLightfv(GL_LIGHT3, GL_LINEAR_ATTENUATION ,light_attenuation3 );

	glMaterialf(GL_FRONT, GL_SHININESS, 100.0f);
	glMaterialfv(GL_FRONT, GL_SPECULAR, light_specular);	
	glEnable(GL_NORMALIZE);
	Image* image = loadBMP("./image/e.bmp");
	_textureId1 = loadTexture(image);

	Image* image1 = loadBMP("./image/e.bmp");
	_textureId = loadTexture(image1);
	Image* image2 = loadBMP("./image/m.bmp");
	_textureId2 = loadTexture(image2);
	Image* image3 = loadBMP("./image/l.bmp");
	_textureId3 = loadTexture(image3);
	Image* image4 = loadBMP("./image/p.bmp");
	_textureId4 = loadTexture(image4);
	Image* image5 = loadBMP("./image/y.bmp");
	_textureId5 = loadTexture(image5);
	Image* image6 = loadBMP("./image/shirt.bmp");
	_textureId6 = loadTexture(image6);
	Image* image7 = loadBMP("./image/wall.bmp");
	_textureId7 = loadTexture(image7);
Image* image8 = loadBMP("./image/roof.bmp");
	_textureId8 = loadTexture(image8);
Image* image9 = loadBMP("./image/floor.bmp");
	_textureId9 = loadTexture(image9);
Image* image10 = loadBMP("./image/table.bmp");
	_textureId10 = loadTexture(image10);
Image* image11 = loadBMP("./image/chair.bmp");
	_textureId11 = loadTexture(image11);
Image* image12 = loadBMP("./image/lampshade.bmp");
	_textureId12 = loadTexture(image12);
Image* image13 = loadBMP("./image/lampbase.bmp");
	_textureId13 = loadTexture(image13);
Image* image14 = loadBMP("./image/cupboard.bmp");
	_textureId14 = loadTexture(image14);
Image* image15 = loadBMP("./image/door.bmp");
	_textureId15 = loadTexture(image15);
Image* image16 = loadBMP("./image/doorknob.bmp");
	_textureId16 = loadTexture(image16);
Image* image17 = loadBMP("./image/musicbox.bmp");
	_textureId17 = loadTexture(image17);
	delete image;
	delete image1;
	delete image2;
	delete image3;
	delete image4;
	delete image5;
	delete image6;
	delete image7;
	delete image8;
	delete image9;
	delete image10;
	delete image11;
	delete image12;
	delete image13;
	delete image14;
	delete image15;
	delete image16;
	delete image17;
}

